/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ClickRouteImport } from './routes/click'
import { Route as AllclickRouteImport } from './routes/allclick'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ClickRoute = ClickRouteImport.update({
  id: '/click',
  path: '/click',
  getParentRoute: () => rootRouteImport,
} as any)
const AllclickRoute = AllclickRouteImport.update({
  id: '/allclick',
  path: '/allclick',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allclick': typeof AllclickRoute
  '/click': typeof ClickRoute
  '/content': typeof ContentRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allclick': typeof AllclickRoute
  '/click': typeof ClickRoute
  '/content': typeof ContentRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allclick': typeof AllclickRoute
  '/click': typeof ClickRoute
  '/content': typeof ContentRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/allclick' | '/click' | '/content' | '/work'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/allclick' | '/click' | '/content' | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/allclick'
    | '/click'
    | '/content'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AllclickRoute: typeof AllclickRoute
  ClickRoute: typeof ClickRoute
  ContentRoute: typeof ContentRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/click': {
      id: '/click'
      path: '/click'
      fullPath: '/click'
      preLoaderRoute: typeof ClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allclick': {
      id: '/allclick'
      path: '/allclick'
      fullPath: '/allclick'
      preLoaderRoute: typeof AllclickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AllclickRoute: AllclickRoute,
  ClickRoute: ClickRoute,
  ContentRoute: ContentRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
